name: Generate Profile Artifacts

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      # ğŸ Generate Snake
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: suirfan20
          outputs: |
            output/github-contribution-grid-snake.svg

      # ğŸ§Š Generate 3D Contribution
      - name: Generate 3D Contribution
        uses: yoshi389111/github-profile-3d-contrib@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: suirfan20

      # ğŸ’¾ Commit changes
      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update profile animations"
