name: Generate Profile Artifacts

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: suirfan20
          outputs: |
            output/github-contribution-grid-snake.svg

      - name: Generate 3D Contribution
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        with:
          github_user_name: suirfan20
          output_dir: output/profile-3d-contrib

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update profile animations"
